name: sdp_transform
version: 0.3.1
description: Dart implementation of sdp-transform
homepage: https://github.com/cloudwebrtc/dart-sdp-transform
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.9.3